if c(filename)=="~/database/DHS/world_childsmall1.dta" {
	cap gen year=yearint
	replace year=1993 if id2=="bd3"
	replace year=1996 if id2=="bd1"
	replace year=1994 if id2=="bo3"
	replace year=2003 if id2=="bo4"
	replace year=1992 if id2=="bf1"
	replace year=1998 if id2=="bf2"
	replace year=1996 if id2=="td1"
	replace year=2005 if id2=="co5"
	replace year=1998 if id2=="ci1"
	replace year=1992 if id2=="eg2"
	replace year=1995 if id2=="eg3"
	replace year=1993 if id2=="gh3"
	replace year=1998 if id2=="gh4"
	replace year=1994 if id2=="ht1"
	replace year=2005 if id2=="hn1"
	replace year=1999 if id2=="ia2"
	replace year=2004 if id2=="ls1"
	replace year=2004 if id2=="md3"
	replace year=2004 if id2=="mw1"
	replace year=1995 if id2=="ml2"
	replace year=2003 if id2=="ma3"
	replace year=2003 if id2=="mz2"
	replace year=1997 if id2=="nc1"
	replace year=1991 if id2=="pk1"
	replace year=1992 if id2=="sn3"
	replace year=1992 if id2=="tz3"
	replace year=2004 if id2=="tz2"
	replace year=2000 if id2=="ug3"
	replace year=1996 if id2=="zm2"
	replace year=2001 if id2=="zm3"

	*replace country="CongoBr" if country==" "
	*replace country="Cote D Ivoire" if country==" "
	*replace country="Cote D Ivoire" if country==" "
	*replace country="DominicanRepublic" if country==" "
	*replace country="DominicanRepublic" if country==" "
	*replace country="DominicanRepublic" if country==" "
	*replace country="DominicanRepublic" if country==" "
	

	gen income_status=	"LOWERMIDDLE"	if country=="Albania"
	replace income_status=	"LOWERMIDDLE"	if country=="Armenia"
	replace income_status=	"UPPERMIDDLE"	if country=="Azerbaijan"
	replace income_status=	"LOWINCOME"	if country=="Bangladesh"
	replace income_status=	"LOWINCOME"	if country=="Benin"
	replace income_status=	"LOWERMIDDLE"	if country=="Bolivia"
	replace income_status=	"UPPERMIDDLE"	if country=="Brazil"
	replace income_status=	"LOWINCOME"	if country=="Burkina Faso"
	replace income_status=	"LOWINCOME"	if country=="Burundi"
	replace income_status=	"LOWINCOME"	if country=="Cambodia"
	replace income_status=	"LOWERMIDDLE"	if country=="Cameroon"
	replace income_status=	"LOWERMIDDLE"	if country=="Cape-Verde"
	replace income_status=	"LOWINCOME"	if country=="CAR"
	replace income_status=	"LOWINCOME"	if country=="Chad"
	replace income_status=	"UPPERMIDDLE"	if country=="Colombia"
	replace income_status=	"LOWINCOME"	if country=="Comoros"
	replace income_status=	"LOWERMIDDLE"	if country=="Congo-Brazzaville"
	replace income_status=	"LOWINCOME"	if country=="Congo"
	replace income_status=	"LOWERMIDDLE"	if country=="Cote d'Ivoire"
	replace income_status=	"UPPERMIDDLE"	if country=="Dominican Republic"
	replace income_status=	"LOWERMIDDLE"	if country=="Egypt"
	replace income_status=	"LOWINCOME"	if country=="Eritrea"
	replace income_status=	"LOWINCOME"	if country=="Ethiopia"
	replace income_status=	"UPPERMIDDLE"	if country=="Gabon"
	replace income_status=	"LOWERMIDDLE"	if country=="Ghana"
	replace income_status=	"LOWERMIDDLE"	if country=="Guatemala"
	replace income_status=	"LOWINCOME"	if country=="Guinea"
	replace income_status=	"LOWERMIDDLE"	if country=="Guyana"
	replace income_status=	"LOWINCOME"	if country=="Haiti"
	replace income_status=	"LOWERMIDDLE"	if country=="Honduras"
	replace income_status=	"LOWERMIDDLE"	if country=="India"
	replace income_status=	"LOWERMIDDLE"	if country=="Indonesia"
	replace income_status=	"UPPERMIDDLE"	if country=="Jordan"
	replace income_status=	"UPPERMIDDLE"	if country=="Kazakhstan"
	replace income_status=	"LOWINCOME"	if country=="Kenya"
	replace income_status=	"LOWINCOME"	if country=="Kyrgyz Republic"
	replace income_status=	"LOWERMIDDLE"	if country=="Lesotho"
	replace income_status=	"LOWINCOME"	if country=="Liberia"
	replace income_status=	"LOWINCOME"	if country=="Madagascar"
	replace income_status=	"LOWINCOME"	if country=="Malawi"
	replace income_status=	"UPPERMIDDLE"	if country=="Maldives"
	replace income_status=	"LOWINCOME"	if country=="Mali"
	replace income_status=	"LOWINCOME"	if country=="Mauritania"
	replace income_status=	"LOWERMIDDLE"	if country=="Moldova"
	replace income_status=	"LOWERMIDDLE"	if country=="Morocco"
	replace income_status=	"LOWINCOME"	if country=="Mozambique"
	replace income_status=	"UPPERMIDDLE"	if country=="Namibia"
	replace income_status=	"LOWINCOME"	if country=="Nepal"
	replace income_status=	"LOWERMIDDLE"	if country=="Nicaragua"
	replace income_status=	"LOWINCOME"	if country=="Niger"
	replace income_status=	"LOWERMIDDLE"	if country=="Nigeria"
	replace income_status=	"LOWERMIDDLE"	if country=="Pakistan"
	replace income_status=	"LOWERMIDDLE"	if country=="Paraguay"
	replace income_status=	"UPPERMIDDLE"	if country=="Peru"
	replace income_status=	"LOWERMIDDLE"	if country=="Philippines"
	replace income_status=	"LOWINCOME"	if country=="Rwanda"
	replace income_status=	"LOWERMIDDLE"	if country=="Samoa"
	replace income_status=	"LOWERMIDDLE"	if country=="Sao-Tome-and-Principe"
	replace income_status=	"LOWERMIDDLE"	if country=="Senegal"
	replace income_status=	"LOWINCOME"	if country=="Sierra-Leone"
	replace income_status=	"UPPERMIDDLE"	if country=="South Africa"
	replace income_status=	"LOWERMIDDLE"	if country=="Sri Lanka"
	replace income_status=	"LOWERMIDDLE"	if country=="Sudan"
	replace income_status=	"LOWERMIDDLE"	if country=="Swaziland"
	replace income_status=	"LOWINCOME"	if country=="Tanzania"
	replace income_status=	"LOWERMIDDLE"	if country=="Timor-Leste"
	replace income_status=	"LOWINCOME"	if country=="Togo"
	replace income_status=	"UPPERMIDDLE"	if country=="Turkey"
	replace income_status=	"UPPERMIDDLE"	if country=="Turkmenistan"
	replace income_status=	"LOWINCOME"	if country=="Uganda"
	replace income_status=	"LOWERMIDDLE"	if country=="Ukraine"
	replace income_status=	"LOWERMIDDLE"	if country=="Uzbekistan"
	replace income_status=	"LOWERMIDDLE"	if country=="Vietnam"
	replace income_status=	"LOWERMIDDLE"	if country=="Yemen"
	replace income_status=	"LOWERMIDDLE"	if country=="Zambia"
	replace income_status=	"LOWINCOME"	if country=="Zimbabwe"
}

else {
	*THIS IS NOT NECESSARY FOR THE MERGE.  THIS WAS FOR A SEPERATE VARIABLE.
	gen income_status=	"LOWERMIDDLE"	if country=="Albania"
	replace income_status=	"LOWERMIDDLE"	if country=="Armenia"
	replace income_status=	"UPPERMIDDLE"	if country=="Azerbaijan"
	replace income_status=	"LOWINCOME"	if country=="Bangladesh"
	replace income_status=	"LOWINCOME"	if country=="Benin"
	replace income_status=	"LOWERMIDDLE"	if country=="Bolivia"
	replace income_status=	"UPPERMIDDLE"	if country=="Brazil"
	replace income_status=	"LOWINCOME"	if country=="Burkina-Faso"
	replace income_status=	"LOWINCOME"	if country=="Burundi"
	replace income_status=	"LOWINCOME"	if country=="Cambodia"
	replace income_status=	"LOWERMIDDLE"	if country=="Cameroon"
	replace income_status=	"LOWERMIDDLE"	if country=="Cape-Verde"
	replace income_status=	"LOWINCOME"	if country=="CAR"
	replace income_status=	"LOWINCOME"	if country=="Chad"
	replace income_status=	"UPPERMIDDLE"	if country=="Colombia"
	replace income_status=	"LOWINCOME"	if country=="Comoros"
	replace income_status=	"LOWERMIDDLE"	if country=="Congo-Brazzaville"
	replace income_status=	"LOWINCOME"	if country=="Congo-Democratic-Republic"
	replace income_status=	"LOWERMIDDLE"	if country=="Cote-d-Ivoire"
	replace income_status=	"UPPERMIDDLE"	if country=="Dominican-Republic"
	replace income_status=	"LOWERMIDDLE"	if country=="Egypt"
	replace income_status=	"LOWINCOME"	if country=="Eritrea"
	replace income_status=	"LOWINCOME"	if country=="Ethiopia"
	replace income_status=	"UPPERMIDDLE"	if country=="Gabon"
	replace income_status=	"LOWERMIDDLE"	if country=="Ghana"
	replace income_status=	"LOWERMIDDLE"	if country=="Guatemala"
	replace income_status=	"LOWINCOME"	if country=="Guinea"
	replace income_status=	"LOWERMIDDLE"	if country=="Guyana"
	replace income_status=	"LOWINCOME"	if country=="Haiti"
	replace income_status=	"LOWERMIDDLE"	if country=="Honduras"
	replace income_status=	"LOWERMIDDLE"	if country=="India"
	replace income_status=	"LOWERMIDDLE"	if country=="Indonesia"
	replace income_status=	"UPPERMIDDLE"	if country=="Jordan"
	replace income_status=	"UPPERMIDDLE"	if country=="Kazakhstan"
	replace income_status=	"LOWINCOME"	if country=="Kenya"
	replace income_status=	"LOWINCOME"	if country=="Kyrgyz-Republic"
	replace income_status=	"LOWERMIDDLE"	if country=="Lesotho"
	replace income_status=	"LOWINCOME"	if country=="Liberia"
	replace income_status=	"LOWINCOME"	if country=="Madagascar"
	replace income_status=	"LOWINCOME"	if country=="Malawi"
	replace income_status=	"UPPERMIDDLE"	if country=="Maldives"
	replace income_status=	"LOWINCOME"	if country=="Mali"
	replace income_status=	"LOWINCOME"	if country=="Mauritania"
	replace income_status=	"LOWERMIDDLE"	if country=="Moldova"
	replace income_status=	"LOWERMIDDLE"	if country=="Morocco"
	replace income_status=	"LOWINCOME"	if country=="Mozambique"
	replace income_status=	"UPPERMIDDLE"	if country=="Namibia"
	replace income_status=	"LOWINCOME"	if country=="Nepal"
	replace income_status=	"LOWERMIDDLE"	if country=="Nicaragua"
	replace income_status=	"LOWINCOME"	if country=="Niger"
	replace income_status=	"LOWERMIDDLE"	if country=="Nigeria"
	replace income_status=	"LOWERMIDDLE"	if country=="Pakistan"
	replace income_status=	"LOWERMIDDLE"	if country=="Paraguay"
	replace income_status=	"UPPERMIDDLE"	if country=="Peru"
	replace income_status=	"LOWERMIDDLE"	if country=="Philippines"
	replace income_status=	"LOWINCOME"	if country=="Rwanda"
	replace income_status=	"LOWERMIDDLE"	if country=="Samoa"
	replace income_status=	"LOWERMIDDLE"	if country=="Sao-Tome-and-Principe"
	replace income_status=	"LOWERMIDDLE"	if country=="Senegal"
	replace income_status=	"LOWINCOME"	if country=="Sierra-Leone"
	replace income_status=	"UPPERMIDDLE"	if country=="South-Africa"
	replace income_status=	"LOWERMIDDLE"	if country=="Sri-Lanka"
	replace income_status=	"LOWERMIDDLE"	if country=="Sudan"
	replace income_status=	"LOWERMIDDLE"	if country=="Swaziland"
	replace income_status=	"LOWINCOME"	if country=="Tanzania"
	replace income_status=	"LOWERMIDDLE"	if country=="Timor-Leste"
	replace income_status=	"LOWINCOME"	if country=="Togo"
	replace income_status=	"UPPERMIDDLE"	if country=="Turkey"
	replace income_status=	"UPPERMIDDLE"	if country=="Turkmenistan"
	replace income_status=	"LOWINCOME"	if country=="Uganda"
	replace income_status=	"LOWERMIDDLE"	if country=="Ukraine"
	replace income_status=	"LOWERMIDDLE"	if country=="Uzbekistan"
	replace income_status=	"LOWERMIDDLE"	if country=="Vietnam"
	replace income_status=	"LOWERMIDDLE"	if country=="Yemen"
	replace income_status=	"LOWERMIDDLE"	if country=="Zambia"
	replace income_status=	"LOWINCOME"	if country=="Zimbabwe"
}
*THIS COMES FROM WORLD BANK ATLAS METHOD (http://data.worldbank.org/about/country-classifications)
*ACTUAL CLASSIFICATION IS HERE: (http://data.worldbank.org/about/country-classifications/country-and-lending-groups#Low_income)

